#!/bin/bash

#parm1 filename
#parm2 key
#return value
#desc get value with key form properties file
function get_prop()
{
	key=$2
	cat $1 | while read line
	do
		need_ignore=$(echo $line | awk 'BEGIN{ret=0} /^#/{ret=1} /^$/{ret=1} END{print ret}')
		if [ $need_ignore -eq 1 ];then
			continue
		fi
		field=$(echo $line | awk -F= '{gsub(" |\t","",$1); print $1}')
		value=$(echo $line | awk 'gsub(/^ *| *$/,"")' | awk -F= '{gsub("\t","",$2); print $2}')
		if [ "X$key" = "X$field" ];then	
			echo $value
			break
		fi	
	done
}

#parm1 filename
#parm2 key
#parm3 value
#desc set value with key form properties file
function set_prop()
{
	i=0
	key=$2
	value=$3
	cat $1 | while read line
	do
		((i+=1))
		need_ignore=$(echo $line | awk 'BEGIN{ret=0} /^#/{ret=1} /^$/{ret=1} END{print ret}')
		if [ $need_ignore -eq 1 ];then
			continue
		fi
		field=$(echo $line | awk -F= '{gsub(" |\t","",$1); print $1}')
		if [ "X$key" = "X$field" ];then	
			sed -i "${i}c\
			${key}=${value}" $1
			break
		fi
	done
}

#parm1 filename
#return 0:ok
#desc  check the ini file is ok or not.
function check_int_syntax()
{
	if [ ! -f $1 ];then 
		return 1
	fi
	ret=$(awk -F= 'BEGIN{valid=1}
	{
		if(valid == 0) next	
		if(length($0) == 0) next
		gsub(" |\t","",$0)	
		head_char=substr($0,1,1)
		if (head_char != "#"){
			if( NF == 1){
				b=substr($0,1,1)
				len=length($0)
				e=substr($0,len,1)
				if (b != "[" || e != "]"){
					valid=0
				}
			}else if( NF == 2){
				b=substr($0,1,1)
				if (b == "["){
					valid=0
				}
			}else{
				valid=0
			}	
		}
	}
	END{print valid}' $1)
	if [ $ret -eq 1 ];then
		return 0
	else
		return 2
	fi
}

#parm1 filename
#parm2 block name
#parm3 key
#return value
#desc get value with key form ini file
function get_field_value()
{
	if [ ! -f $1 ] || [ $# -ne 3 ];then
		return 1
	fi
	blockname=$2
	fieldname=$3
	begin_block=0
	end_block=0
	cat $1 | while read line
	do
		if [ "X$line" = "X[$blockname]" ];then
			begin_block=1
			continue
		fi
		if [ $begin_block -eq 1 ];then
			end_block=$(echo $line | awk 'BEGIN{ret=0} /^\[.*\]$/{ret=1} END{print ret}')
			if [ $end_block -eq 1 ];then
				#echo "end block"
				break
			fi
			need_ignore=$(echo $line | awk 'BEGIN{ret=0} /^#/{ret=1} /^$/{ret=1} END{print ret}')
			if [ $need_ignore -eq 1 ];then
				#echo "ignored line:" $line
				continue
			fi
			field=$(echo $line | awk -F= '{gsub(" |\t","",$1); print $1}')
			value=$(echo $line | awk 'gsub(/^ *| *$/,"")' | awk -F= '{gsub("\t","",$2); print $2}')
			#echo "'$field':'$value'"
			if [ "X$fieldname" = "X$field" ];then	
				#echo "result value:'$result'"
				echo $value
				break
			fi
		fi
	done
	return 0
}

#parm1 filename
#parm2 block name
#parm3 key
#parm4 value
#desc set value with key form ini file
function set_field_value()
{
	i=0
	if [ ! -f $1 ] || [ $# -ne 4 ];then
		return 1
	fi
	blockname=$2
	fieldname=$3
	value=$4
	begin_block=0
	end_block=0
	cat $1 | while read line
	do
        ((i+=1))
		if [ "X$line" = "X[$blockname]" ];then
			begin_block=1
			continue
		fi
		if [ $begin_block -eq 1 ];then
			end_block=$(echo $line | awk 'BEGIN{ret=0} /^\[.*\]$/{ret=1} END{print ret}')
			if [ $end_block -eq 1 ];then
				break
			fi
			need_ignore=$(echo $line | awk 'BEGIN{ret=0} /^#/{ret=1} /^$/{ret=1} END{print ret}')
			if [ $need_ignore -eq 1 ];then
				continue
			fi
			field=$(echo $line | awk -F= '{gsub(" |\t","",$1); print $1}')
			if [ "X$fieldname" = "X$field" ];then	
				sed -i "${i}c\
				${field}=${value}" $1
				break
			fi
		fi
	done
	return 0
}

#parm1 the value string of radio(eg.0-Y)
#desc get the value of string(Such as get "0" from "0-1")
function get_radio_value()
{
	OLD_IFS="$IFS" 
	IFS="-" 
	arr=($1) 
	IFS="$OLD_IFS" 
	for s in ${arr[@]} 
	do 
        echo "$s" 
        break
	done
}
